# fly.toml app configuration file generated for dhcdev on 2023-11-02T23:13:06+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dhcdev"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
